### ISSUE TITLE
 [CRITICAL] Unrecoverable error: OSError(19, 'No such device')

### ISSUE THREAD

**Issue by ohheyitsFarci** [mikenye/docker-striparr#23]
I'm getting this error message with my fresh install. It just constantly loops as soon as the container starts. The container does not crash. The only thing that changes between each error is the "app:         striparr:0x7fac3b96cf60" portion.
I had it running on my old server setup without issue.
Running OMV 5.6.14-1 with Docker 5:20.10.8-3-0-debian-buster

Error Log:

```
today at 3:35:44 PM [worker] [2021-09-09 05:35:44,691] [CRITICAL] Unrecoverable error: OSError(19, 'No such device')
today at 3:35:44 PM [worker] Traceback (most recent call last):
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/celery/worker/worker.py", line 203, in start
today at 3:35:44 PM [worker]     self.blueprint.start(self)
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/celery/bootsteps.py", line 116, in start
today at 3:35:44 PM [worker]     step.start(parent)
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/celery/bootsteps.py", line 365, in start
today at 3:35:44 PM [worker]     return self.obj.start()
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/celery/concurrency/base.py", line 129, in start
today at 3:35:44 PM [worker]     self.on_start()
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/celery/concurrency/prefork.py", line 113, in on_start
today at 3:35:44 PM [worker]     **self.options)
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/celery/concurrency/asynpool.py", line 460, in __init__
today at 3:35:44 PM [worker]     super().__init__(processes, *args, **kwargs)
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/billiard/pool.py", line 1046, in __init__
today at 3:35:44 PM [worker]     self._create_worker_process(i)
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/celery/concurrency/asynpool.py", line 477, in _create_worker_process
today at 3:35:44 PM [worker]     return super()._create_worker_process(i)
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/billiard/pool.py", line 1142, in _create_worker_process
today at 3:35:44 PM [worker]     on_ready_counter = self._ctx.Value('i')
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/billiard/context.py", line 182, in Value
today at 3:35:44 PM [worker]     ctx=self.get_context())
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/billiard/sharedctypes.py", line 78, in Value
today at 3:35:44 PM [worker]     obj = RawValue(typecode_or_type, *args)
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/billiard/sharedctypes.py", line 46, in RawValue
today at 3:35:44 PM [worker]     obj = _new_value(type_)
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/billiard/sharedctypes.py", line 37, in _new_value
today at 3:35:44 PM [worker]     wrapper = heap.BufferWrapper(size)
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/billiard/heap.py", line 274, in __init__
today at 3:35:44 PM [worker]     block = BufferWrapper._heap.malloc(size)
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/billiard/heap.py", line 255, in malloc
today at 3:35:44 PM [worker]     (arena, start, stop) = self._malloc(size)
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/billiard/heap.py", line 152, in _malloc
today at 3:35:44 PM [worker]     arena = Arena(length)
today at 3:35:44 PM [worker]   File "/usr/local/lib/python3.7/dist-packages/billiard/heap.py", line 104, in __init__
today at 3:35:44 PM [worker]     self.buffer = mmap.mmap(self.fd, self.size)
today at 3:35:44 PM [worker] OSError: [Errno 19] No such device
today at 3:35:45 PM [worker]  
today at 3:35:45 PM [worker]  -------------- celery@5546c665aa68 v5.0.5 (singularity)
today at 3:35:45 PM [worker] --- ***** ----- 
today at 3:35:45 PM [worker] -- ******* ---- Linux-5.10.0-0.bpo.8-amd64-x86_64-with-debian-10.8 2021-09-09 05:35:45
today at 3:35:45 PM [worker] - *** --- * --- 
today at 3:35:45 PM [worker] - ** ---------- [config]
today at 3:35:45 PM [worker] - ** ---------- .> app:         striparr:0x7fac3b96cf60
today at 3:35:45 PM [worker] - ** ---------- .> transport:   redis://localhost:6379/0
today at 3:35:45 PM [worker] - ** ---------- .> results:     redis://localhost:6379/0
today at 3:35:45 PM [worker] - *** --- * --- .> concurrency: 1 (prefork)
today at 3:35:45 PM [worker] -- ******* ---- .> task events: OFF (enable -E to monitor tasks in this worker)
today at 3:35:45 PM [worker] --- ***** ----- 
today at 3:35:45 PM [worker]  -------------- [queues]
today at 3:35:45 PM [worker]                 .> celery           exchange=celery(direct) key=celery
today at 3:35:45 PM [worker]                 
today at 3:35:45 PM [worker] 
today at 3:35:45 PM [worker] [tasks]
today at 3:35:45 PM [worker]   . striparr.worker
today at 3:35:45 PM [worker] 
```

**Comment by ohheyitsFarci** [comment]
I managed to get it to work with some troubleshooting.
It turns out it didn't like me assigning a different location for /tmp. I'm not sure why it worked before but not now, maybe a permissions thing? Either way its working again with the default /tmp location.

**Comment by mikenye** [comment]
I'm glad you got it sorted!
